
export const SET_GITHUB_KEY = 'SET_GITHUB_KEY';
export const SET_GITHUB_KEY_SUCCESS = 'SET_GITHUB_KET_SUCCESS';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USER_REPOS_SUCCESS = 'GET_USER_REPOS_SUCCESS';

export const SET_ACTIVE_REPO = 'SET_ACTIVE_REPO';

export const GET_USER_REPO_ISSUES_SUCCESS = 'GET_USER_REPO_ISSUES_SUCCESS';

export const SET_ISSUE_RANK = 'SET_ISSUE_RANK';
